Parameters:
  EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: project_iac_udacity
  P_CIDR_vpc: 
        Description: VPC IP Address Range
        Type: String
        Default: 10.0.0.0/16
  P_CIDR_private_subnet_01:
        Description: Availability Zone 1 Private Subnet IP Address Range
        Type: String
        Default: 10.0.1.0/24
  P_CIDR_private_subnet_02:
        Description: Availability Zone 2 Private Subnet IP Address Range
        Type: String
        Default: 10.0.2.0/24
  P_CIDR_public_subnet_01:
        Description: Availability Zone 1 Public Subnet IP Address Range
        Type: String
        Default: 10.0.3.0/24
  P_CIDR_public_subnet_02:
        Description: Availability Zone 2 Public Subnet IP Address Range
        Type: String
        Default: 10.0.4.0/24

Resources:

  #########################
  ######### VPC ###########
  #########################
  
  VPC_HA_WebApp: 
    Type : AWS::EC2::VPC
    Properties:
      Cid rBlock: !Ref P_CIDR_vpc
      EnableDnsHostnames: true


  #########################
  ######## SUBNETS ########
  #########################

  SUBNET_private_01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC_HA_WebApp 
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref P_CIDR_private_subnet_01
      MapPublicIpOnLaunch: false


  SUBNET_private_02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC_HA_WebApp
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref P_CIDR_private_subnet_02
      MapPublicIpOnLaunch: false
      
    
  SUBNET_public_01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC_HA_WebApp 
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref P_CIDR_public_subnet_01
      MapPublicIpOnLaunch: false


  SUBNET_public_02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC_HA_WebApp
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref P_CIDR_public_subnet_02
      MapPublicIpOnLaunch: false


  #########################
  #### INTERNETGATEWAY ####
  #########################

  INTERNETGW_01: 
    Type: AWS::EC2::InternetGateway


  VPCGWATTA_01:
    Type:  AWS::EC2::VPCGatewayAttachment 
    Properties: 
      VpcId: !Ref VPC_HA_WebApp 
      InternetGatewayId: !Ref INTERNETGW_01


  #########################
  ########## NAT ##########
  #########################

  EIP_NATGateway_01:
    Type: AWS::EC2::EIP
    DependsOn: INTERNETGW_01
    Properties: 
      Domain: vpc


  EIP_NATGateway_02:
    Type: AWS::EC2::EIP
    DependsOn: INTERNETGW_01
    Properties:
      Domain: vpc


  NATGW_01: 
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt EIP_NATGateway_01.AllocationId
      SubnetId: !Ref SUBNET_public_01


  NATGW_02: 
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP_NATGateway_02.AllocationId
      SubnetId: !Ref SUBNET_public_02
   
   
  #########################
  ######## ROUTES #########
  #########################
    
  ROUTETABLE_public_01:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC_HA_WebApp

  ROUTE_public_01: 
    Type: AWS::EC2::Route
    DependsOn: VPCGWATTA_01
    Properties: 
      RouteTableId: !Ref ROUTERTABLE_public_01
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref INTERNETGW_01


  ROUTETABLE_private_01:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC_HA_WebApp

  ROUTE_private_01:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ROUTETABLE_private_01
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGW_01


  ROUTETABLE_private_02:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC_HA_WebApp

  ROUTE_private_02:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ROUTETABLE_private_02
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGW_02


  #########################
  ###### ROUTE ASSOC ######
  #########################

  SUBNROUTEASSOC_public_01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ROUTETABLE_public_01 
       SubnetId: !Ref SUBNET_public_01


  SUBNROUTEASSOC_public_02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ROUTETABLE_public_02
       SubnetId: !Ref SUBNET_public_02

 
  SUBNROUTEASSOC_private_01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ROUTETABLE_private_01
       SubnetId: !Ref SUBNET_private_01

    
  SUBNROUTEASSOC_private_02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ROUTETABLE_private_02
       SubnetId: !Ref SUBNET_private_02





Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPC-ID

  VPCPublicRouteTable:
    Description: Public Routing
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub ${EnvironmentName}-PUB-RT

  VPCPrivateRouteTable1:
    Description: Private Routing AZ1
    Value: !Ref PrivateRouteTable1
    Export:
      Name: !Sub ${EnvironmentName}-PRIV1-RT

  VPCPrivateRouteTable2:
    Description: Private Routing AZ2
    Value: !Ref PrivateRouteTable2
    Export:
      Name: !Sub ${EnvironmentName}-PRIV2-RT

  PublicSubnets:
    Description: A list of public subnets
    Value: !Join [",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
    Export:
      Name: !Sub ${EnvironmentName}-PUB-NETS

  PrivateSubnets:
    Description: A list of private subnets
    Value: !Join [",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]
    Export:
      Name: !Sub ${EnvironmentName}-PRIV-NETS

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PUB1-SN

  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${EnvironmentName}-PUB2-SN

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PRIV1-SN

  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${EnvironmentName}-PRIV2-SN
      
      
 
